const TOM_SAX_DATA = {
  profile:{name:'Tom Sax',tagline:'Saxophoniste événementiel & live performer',instagram:'https://www.instagram.com/tomsaxoff/',handle:'@tomsaxoff'},
  media:[
    {id:'m1',type:'Live',title:'Mariage — soirée',occasion:'Dancefloor',url:'https://www.instagram.com/tomsaxoff/',thumbnail:'assets/images/webp/07-dj-dancefloor.webp'},
    {id:'m2',type:'Live',title:'Cocktail en extérieur',occasion:'Réception',url:'https://www.instagram.com/tomsaxoff/',thumbnail:'assets/images/webp/05-garden-cocktail.webp'},
    {id:'m3',type:'Live',title:'Performance au coucher du soleil',occasion:'Wedding',url:'https://www.instagram.com/tomsaxoff/',thumbnail:'assets/images/webp/01-sunset-back.webp'},
    {id:'m4',type:'Live',title:'Soirée & invités',occasion:'Mariage',url:'https://www.instagram.com/tomsaxoff/',thumbnail:'assets/images/webp/09-wedding-dance.webp'}
  ],
  repertoire:[
    ['Saxo Beat','—','Sax moderne'],['No Man No Cry','Jimmy Sax','Sax moderne'],['Una Mattina','Jimmy Sax','Sax moderne'],['Ibiza','Jul x Jimmy Sax','Sax moderne'],['Lily Was Here','Candy Dulfer','Jazz / Lounge'],['One Day / Vandaag','Bakermat','Sax moderne'],['Jubel','Klingande','Sax moderne'],['Punga','Klingande','Sax moderne'],['Only God Can Save Your Soul','Klingande','Sax moderne'],['Changes','Faul & Wad','Sax moderne'],['This Girl','Kungs','Sax moderne'],['Calabria 2007','—','Dance / Club'],['How Gee','—','Sax moderne'],
    ['Thinking Out Loud','Ed Sheeran','Émotion'],['Careless Whisper','George Michael','Émotion'],['When I Was Your Man','Bruno Mars','Émotion'],['Die With A Smile','Bruno Mars & Lady Gaga','Émotion'],['All of Me','John Legend','Émotion'],['I’m Not The Only One','Sam Smith','Émotion'],['Fallin’','Alicia Keys','Émotion'],['If I Ain’t Got You','Alicia Keys','Émotion'],['Love Yourself','Justin Bieber','Émotion'],['La Vie en Rose','Édith Piaf','Émotion'],['L’Hymne à l’amour','Édith Piaf','Émotion'],['La Bohème','Charles Aznavour','Émotion'],['Comme d’habitude','—','Émotion'],['Les gens qui s’aiment','William Sheller','Émotion'],['Sensualité','Axelle Red','Émotion'],['Bésame Mucho','—','Émotion'],['Ti Amo','—','Émotion'],['Alléluia','—','Émotion'],
    ['Suavemente','Soolking','Latino'],['My Salsa','Franglish','Latino'],['Havana','—','Latino'],['Señorita','—','Latino'],['Contra La Pared','Sean Paul & J Balvin','Latino'],['Danza Kuduro','—','Latino'],['Pepas','Farruko','Latino'],['Fireball','Pitbull','Latino'],['Andalouse','Kendji Girac','Latino'],['Gitano','Kendji Girac','Latino'],['Cool','Kendji Girac','Latino'],['Baiana','—','Latino'],['Ma Chérie','—','Latino'],['Welcome to St Tropez','—','Latino'],
    ['Treasure','Bruno Mars','Funk / Groove'],['Uptown Funk','Bruno Mars','Funk / Groove'],['Blurred Lines','Robin Thicke','Funk / Groove'],['Billie Jean','Michael Jackson','Funk / Groove'],['Happy','Pharrell Williams','Funk / Groove'],['Worth It','Fifth Harmony','Funk / Groove'],['Give Me The Night','George Benson','Funk / Groove'],['Street Life','The Crusaders','Funk / Groove'],['Just The Two of Us','Bill Withers','Funk / Groove'],['Isn’t She Lovely','Stevie Wonder','Funk / Groove'],
    ['Attention','Charlie Puth','Pop'],['How Long','Charlie Puth','Pop'],['Sugar','Maroon 5','Pop'],['Girls Like You','Maroon 5','Pop'],['Memories','Maroon 5','Pop'],['I Feel It Coming','The Weeknd','Pop'],['How Deep Is Your Love','—','Pop'],['Bad Guy','Billie Eilish','Pop'],['Dance Monkey','—','Pop'],['Ride It','—','Pop'],['Lose Control','—','Pop'],['Peaches','Justin Bieber','Pop'],['Kiss Me More','Doja Cat','Pop'],['Woman','Doja Cat','Pop'],['Cold Heart','Elton John & Dua Lipa','Pop'],['Talk Dirty','Jason Derulo','Pop'],['Savage Love','Jason Derulo','Pop'],['Dancing','Jason Derulo','Pop'],['Ready or Not','Fugees','Pop'],
    ['Freed From Desire','Gala','Dance / Club'],['The Rhythm of the Night','Corona','Dance / Club'],['Sun Goes Down','Robin Schulz','Dance / Club'],['Paradise','DJ Snake','Dance / Club'],['Let’s Go','Jaden Bojsen','Dance / Club'],['Jérusalema','—','Dance / Club'],['Melodrama','—','Dance / Club'],
    ['Salé','Niska','Urbain / Afro'],['Kalash','Niska','Urbain / Afro'],['Spider','Gims','Urbain / Afro'],['Parisienne','Gims','Urbain / Afro'],['Ninao','Gims','Urbain / Afro'],['Catchu','L’Artiste','Urbain / Afro'],['Chocolat','L’Artiste','Urbain / Afro'],['Joli Bébé','Naza','Urbain / Afro'],['Avec Classe','Corneille & Aya Nakamura','Urbain / Afro'],['Morose','Damso','Urbain / Afro'],['Mwaka Moon','Damso & Kalash','Urbain / Afro'],['N’y pense plus','Tayc','Urbain / Afro'],['Dodo','Tayc','Urbain / Afro'],['Laisse-moi','Keblack','Urbain / Afro'],['Match Nul','Éloquence','Urbain / Afro'],['Ne reviens pas','Heuss L’enfoiré','Urbain / Afro'],['Femme Like U','K-Maro','Urbain / Afro'],['Tu m’oublieras','Larusso','Urbain / Afro'],['Un jour je marierai un ange','Pierre de Maere','Urbain / Afro'],
    ['Bella Ciao','—','Jazz / Lounge'],['Take Five','Dave Brubeck','Jazz / Lounge']
  ].map((s,i)=>({id:'song-'+(i+1),title:s[0],artist:s[1],category:s[2],visible:true,featured:['Careless Whisper','Lily Was Here','Jubel','Calabria 2007','Take Five','La Vie en Rose'].includes(s[0])})),
  demo:{
    leads:[
      {id:'lead-1001',firstName:'Sarah',lastName:'Yanis',email:'sarah@example.com',phone:'06 00 00 00 01',eventType:'Mariage',eventDate:'2027-05-23',location:'Metz',guestCount:'150',moment:'Cocktail + soirée',message:'Nous cherchons une ambiance chic au cocktail puis plus festive avec notre DJ.',status:'Nouveau',createdAt:'2026-09-14T12:00:00.000Z',demo:true},
      {id:'lead-1002',firstName:'Clara',lastName:'Martin',email:'clara@example.com',phone:'06 00 00 00 02',eventType:'Corporate',eventDate:'2027-06-06',location:'Luxembourg',guestCount:'90',moment:'Cocktail',message:'Afterwork clients, format élégant.',status:'À contacter',createdAt:'2026-09-13T14:30:00.000Z',demo:true}
    ],
    events:[
      {id:'evt-1',client:'Sarah & Yanis',date:'2027-05-23',location:'Metz',type:'Mariage',service:'Cocktail + soirée',amount:700,deposit:200,status:'Confirmé',notes:'Prévoir un échange avec le DJ.',playlist:{Cocktail:['Jubel','Lily Was Here'],Ouverture:['Fallin’'],Soirée:['Calabria 2007','Freed From Desire']},demo:true},
      {id:'evt-2',client:'Entreprise Nova',date:'2027-06-06',location:'Luxembourg',type:'Corporate',service:'Cocktail',amount:520,deposit:150,status:'Option',notes:'Installation à confirmer.',playlist:{Cocktail:['Just The Two of Us','Give Me The Night']},demo:true}
    ]
  }
};
window.TOM_SAX_DATA=TOM_SAX_DATA;